### ISSUE TITLE
Register at GitHub

### ISSUE THREAD

**Issue by RodionGork** [RodionGork/troll-test-repo#1]
Please, register at this site to begin. This will allow you to create issues here and reply to mine ones.

After registering do the following:

- change an avatar (I think profile settings are accessible when you click on your icon at the top right)
- add a comment to this issue, to tell that you have succeeded.

**Comment by Trollenok** [comment]
Hi, dear Squirrel!
It was very hard task for my miserable brain, but I did it.
Trollenok

**Comment by RodionGork** [comment]
Everything looks great! Now we can close this issue!
