### ISSUE TITLE
Create an issue about washing machine

### ISSUE THREAD

**Issue by RodionGork** [RodionGork/troll-test-repo#2]
Try to create an issue yourself.

Click on "issues" and find "New Issue". Then add the title like "Try to fix Washing Machine" and add the detailed message below, trying to explain what is wrong. Feel free to use google/yandex translate to find proper words :)

After issue is created, remember it's number and then add a comment here, saying "I've created issue `#N`". It should become link then.

**Comment by Trollenok** [comment]
I've created issue #1
(It is wrong link because it sends to your first issue)
May be this link is better?
https://github.com/Trollenok/trollia-learning/issues/1

**Comment by RodionGork** [comment]
That's very interesting! You've done something more.

Here issues are attached to some project. I've initially created "troll-test-repo" project at "RodionGork" profile. However you've created your own project "trollia-learning" at "Trollenok" profile.

Probably this is even better, and I didn't know the links between them work. :+1:
